### PR TITLE
fixes #1

### LINKED ISSUE #1: github urls
your github urls are using "https://github.com/greenelf" instead of "https://github.com/greenelfx"

the 'x' is missing

also, you might want to use cURL instead of file_get_contents

### PR DESCRIPTION
**Pull request by holthelper**
fixed a few bugs and straightened up the code a bit

### CODE REVIEW

**Comment by holthelper** [comment]
do update #1 and not revert... thought it didnt commit but yea...

**Comment by kedarv** [comment]
Updated via cherry-pick. You may need to reset back to master since your repo is now one "commit" ahead. Thanks for the work!

**Comment by greenelfx** [comment]
Updated via cherry-pick. You may need to reset back to master since your repo is now one "commit" ahead. Thanks for the work!

**Comment by hiroyukims** [comment]
@kedarv what is your Twitter ? send a message please, @hiroyukims.

**Pull request closed without merging**
